### ISSUE TITLE
Sysmon for Splunk App not displaying any data from Windows Event Collector forwarded logs. 

### ISSUE THREAD

**Issue by johnyb0312** [MHaggis/sysmon-splunk-app#2]
Sysmon for Splunk App not displaying any data from Windows Event Collector (we are using Windows Event Collector as a single forwarder). How might I troubleshoot and reconfigure if necessary in my deployed environment?  

Sysmon data is in Splunk.
sourcetype =	WinEventLog:ForwardedEvents

I can see logs in Splunk when I search under  the data feed Host (in my environment is is called): WinEvtCollector		

I tried to adjust the macro using the above sourcetype but that did not work. I think I'm missing some fundamental piece of info here.

Maybe because I'm collecting my logs from a single Windows Event Forwarder and not the individual boxes themselves (maybe)?

It looks like the app is based on the idea that a person would be sending their logs from the windows box straight into the Splunk instance and not through a Windows Event Collector.

Can you provide me any help in understanding this so that I can utilize your app? It looks amazing.

**Comment by olafhartong** [comment]
Are you sure you are searching in the correct index? If so can you make sure the data is parsed as XML, the fields should be properly extracted in order for the app to work.

You also need to have the Splunk for Sysmon TA installed

**Comment by johnyb0312** [comment]
It was installed. I was using both the Sysmon TA nad Sysmon for Splunk apps.  I have deleted them both. I'm going to reinstall just the Sysmon TA and see what happens.

**Comment by johnyb0312** [comment]
So I have fixed it and in doing so I have learned a lot.  For those who would follow in my foot steps.

Their are multiple "Sysmon" apps in the splunk app store.

You must download the Sysmon TA app first. Official name is: Microsoft Sysmon Add-on (Folder Name TA-Microsoft-sysmon)

This will add another data source under your Splunk data sources. In my deployment I am pulling sysmon data from a Windows event collector which is my first data source.

The Sysmon TA app appears to reparse that data. Not positive about this but that is my assumption.

When you look at the data from the Sysmon TA app data source it will be in a raw xml format. Basically all mashed together.

Download a second app called Sysmon App for Splunk.

This will parse the information into already built searches on a nice dashboard. Make sure that you hit submit on the time <Last 24 hours (or your setting)> because by default it does not pull the data.

And it is really that simple.

Thanks for the help olafhartong. 

![splunk data sources](https://cloud.githubusercontent.com/assets/17878047/25314585/547b146e-2847-11e7-80e6-73eebaea5593.PNG)

![sysmon app for splunk](https://cloud.githubusercontent.com/assets/17878047/25314584/54780b0c-2847-11e7-8125-f09a582942fa.PNG)

**Comment by MHaggis** [comment]
Hi @johnyb0312,
The steps are outlined on the github Readme and on the Splunkbase setup guide. Did you see them?  Are they clear enough on the setup?

**Comment by johnyb0312** [comment]
So, I posted above because I feel some background about the different apps would help. And since I am new to this I wanted to share my struggle with anyone else that may also need assistance.

I'm working on a dev version of my deployment (and was able to get it completely working).  However, my production will not display the logs from the TA. A guide that really helps understand what the system is doing would assist in troubleshooting.

So, although what was posted is accurate, I would love a little more depth (just because I'm so new to this).

If you happen to know why the data source from the TA is not displaying or where to look for troubleshooting, that would be most helpful.  I will continue to look.

Thank you for your response.
