### ISSUE TITLE
Critical Process Report

### ISSUE THREAD

**Issue by mstarks01** [MHaggis/sysmon-splunk-app#5]
The Critical Process Report appears to be expecting the executable names to be preceded by *\\, but they are expanded simply as the exe name (i.e. cmd.exe). So, the report returns nothing as written.

**Comment by mstarks01** [comment]
Same for Net Group, Localgroup report. Maybe others?

**Comment by MHaggis** [comment]
Good catch! I'll get this fixed soon.

**Comment by MHaggis** [comment]
If you have the ability, try this out with some data - https://github.com/MHaggis/sysmon-splunk-app/tree/App-v2
It's been working fine for me the last few days, including all the saved searches.

**Comment by MHaggis** [comment]
I went ahead and merged. See Master Branch

**Comment by mstarks01** [comment]
Thanks!
