### ISSUE TITLE
Sysmon v7.01 and Schema 4.00

### ISSUE THREAD

**Issue by riparino** [MHaggis/sysmon-splunk-app#7]
I've been trying to run this config on Splunk 7.0.2 with Sysmon 7.01 and a cfg on Schema 4.00 and it appears that the parsing isn't working on the app anymore. Are there any plans to update this as it worked great with 6.02

**Comment by MHaggis** [comment]
Hmm yes. I'll begin testing now.

**Comment by riparino** [comment]
I seem to have gotten it working but it required using the Universal Forwarder with "Forwarding and receiving" configured with a receive port rather than the "Data Inputs" method which works if the only thing you're doing is forwarding Sysmon. 

I updated a couple of fields such as "Computer" which is "ComputerName" and I'm running Swift's configuration with the new schema.

**Comment by MHaggis** [comment]
Interesting.

I just checked my lab -
```
System Monitor v7.01 - System activity monitor
Copyright (C) 2014-2018 Mark Russinovich and Thomas Garnier
Sysinternals - www.sysinternals.com
<manifest schemaversion="4.0" binaryversion="1.01">
  <configuration>
```

Things are working good with the latest app I'm working on. I'll upgrade Splunk and confirm again before submitting latest to Git soon.

**Comment by MHaggis** [comment]
I do see `Computer` now. I'll make sure things are updated

**Comment by MHaggis** [comment]
If you have the ability, try this out with some data - https://github.com/MHaggis/sysmon-splunk-app/tree/App-v2
It's been working fine for me the last few days.

**Comment by MHaggis** [comment]
I went ahead and merged. See Master Branch
